version: '2.1'

services:

  database:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      dockerfile: db.Dockerfile
      context: .
    ports:
      - 5432:5432

  opensirene:
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - database
    volumes:
      - .:/home
    entrypoint: /usr/bin/opensirene --config=/home/conf-example.yml
    expose: 
      - 8080
